export {default as Dashboard} from './Dashboard';
export {default as Login} from './Login';
export {default as Enquiry} from './Enquiry';
export {default as BlogList} from './BlogList';
export {default as BlogCatList} from './BlogCatList';
export {default as Orders} from './Orders';
export {default as Customers} from './Customers';
export {default as ColorList} from './ColorList';
export {default as CategoryList} from './CategoryList';
export {default as ProductList} from './ProductList';
export {default as BrandList} from './BrandList';
export {default as AddBlog} from './AddBlog';
export {default as AddBlogCat} from './AddBlogCat';
export {default as  AddColor} from './AddColor';
export {default as AddCat} from './AddCat'
export {default as AddBrand} from './AddBrand'
export {default as AddProduct} from './AddProduct'
export {default as ViewOrder} from './ViewOrder';